language: rust
cache: cargo
rust:
  - 1.27.0
  - stable
  - beta
  - nightly
script:
  - touch examples/common/consumer_key examples/common/consumer_secret
  - cargo build --verbose
  - cargo test --verbose
matrix:
  allow_failures:
    - rust: nightly
